#!/bin/env sh

if [[ ! -f /etc/dconf/profile/gdm ]]; then
  cat <<EE | sudo tee /etc/dconf/profile/gdm >/dev/null
user-db:user
system-db:gdm
file-db:/usr/share/gdm/greeter-dconf-defaults
EE
fi

[[ -d /etc/dconf/db/gdm.d ]] || sudo mkdir -p /etc/dconf/db/gdm.d

if [[ ! -f /etc/dconf/db/gdm.d/10-cursor-settings ]]; then
  cat <<EE | sudo tee /etc/dconf/db/gdm.d/10-cursor-settings >/dev/null
[org/gnome/desktop/interface]
cursor-theme='Bibata-Rainbow-Original'
EE
fi

sudo dconf update
